(defconst my-config-base "~/.emacs.d/")
(load (concat my-config-base "mybase.el"))
(load (concat my-config-base "myfunc.el"))
(load-config "myconfig.el")
(load-config "mypackage.el")
(load-config "mykeydef.el")
(load-config "mycustom.el")
