(defconst my-config-base (file-name-directory load-file-name))
(load (concat my-config-base "myfunc.el"))
(load! "mybase.el")
(load! "myconfig.el")
(load! "mypackage.el")
(load! "mykeyfunc.el")
(load! "mykeydef.el")
(load! "mycustom.el")
